const comics = [
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 1,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2024,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 2,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2024,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 3,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2024,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 4,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 5,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 6,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 7,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 8,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 9,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 10,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 11,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 12,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 13,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 14,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 15,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 16,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 17,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 18,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 19,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 1,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2024,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 2,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2024,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 3,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2024,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 4,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 5,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 6,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 7,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 8,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 9,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 10,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 11,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 12,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 13,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 14,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 15,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 16,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 17,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 18,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 1,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2024,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 2,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2024,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 3,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 4,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 5,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 6,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 7,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 8,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 9,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 10,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 11,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 12,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 13,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 14,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 15,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 16,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 17,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 18,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Flash",
    character: "Flash",
    issue: 1,
    writer: "Jeff Lemire",
    artist: "Nick Robles",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Flash",
    character: "Flash",
    issue: 2,
    writer: "Jeff Lemire",
    artist: "Nick Robles",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Flash",
    character: "Flash",
    issue: 3,
    writer: "Jeff Lemire",
    artist: "Nick Robles",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Flash",
    character: "Flash",
    issue: 4,
    writer: "Jeff Lemire",
    artist: "Nick Robles",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Flash",
    character: "Flash",
    issue: 5,
    writer: "Jeff Lemire",
    artist: "Nick Robles",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Flash",
    character: "Flash",
    issue: 6,
    writer: "Jeff Lemire",
    artist: "Nick Robles",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Flash",
    character: "Flash",
    issue: 7,
    writer: "Jeff Lemire",
    artist: "Nick Robles",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Flash",
    character: "Flash",
    issue: 8,
    writer: "Jeff Lemire",
    artist: "Nick Robles",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Flash",
    character: "Flash",
    issue: 9,
    writer: "Jeff Lemire",
    artist: "Nick Robles",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Flash",
    character: "Flash",
    issue: 10,
    writer: "Jeff Lemire",
    artist: "Nick Robles",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Flash",
    character: "Flash",
    issue: 11,
    writer: "Jeff Lemire",
    artist: "Nick Robles",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Flash",
    character: "Flash",
    issue: 12,
    writer: "Jeff Lemire",
    artist: "Nick Robles",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Flash",
    character: "Flash",
    issue: 13,
    writer: "Jeff Lemire",
    artist: "Nick Robles",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Green Lantern",
    character: "Green Lantern",
    issue: 1,
    writer: "Al Ewing",
    artist: "Jahnoy Lindsay",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Green Lantern",
    character: "Green Lantern",
    issue: 2,
    writer: "Al Ewing",
    artist: "Jahnoy Lindsay",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Green Lantern",
    character: "Green Lantern",
    issue: 3,
    writer: "Al Ewing",
    artist: "Jahnoy Lindsay",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Green Lantern",
    character: "Green Lantern",
    issue: 4,
    writer: "Al Ewing",
    artist: "Jahnoy Lindsay",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Green Lantern",
    character: "Green Lantern",
    issue: 5,
    writer: "Al Ewing",
    artist: "Jahnoy Lindsay",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Green Lantern",
    character: "Green Lantern",
    issue: 6,
    writer: "Al Ewing",
    artist: "Jahnoy Lindsay",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Green Lantern",
    character: "Green Lantern",
    issue: 7,
    writer: "Al Ewing",
    artist: "Jahnoy Lindsay",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Green Lantern",
    character: "Green Lantern",
    issue: 8,
    writer: "Al Ewing",
    artist: "Jahnoy Lindsay",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Green Lantern",
    character: "Green Lantern",
    issue: 9,
    writer: "Al Ewing",
    artist: "Jahnoy Lindsay",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Green Lantern",
    character: "Green Lantern",
    issue: 10,
    writer: "Al Ewing",
    artist: "Jahnoy Lindsay",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Green Lantern",
    character: "Green Lantern",
    issue: 11,
    writer: "Al Ewing",
    artist: "Jahnoy Lindsay",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Green Lantern",
    character: "Green Lantern",
    issue: 12,
    writer: "Al Ewing",
    artist: "Jahnoy Lindsay",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Martian Manhunter",
    character: "Martian Manhunter",
    issue: 1,
    writer: "Deniz Camp",
    artist: "Javier Rodriguez",
    publisher: "DC",
    releaseYear: 2025,
    status: "Limited Series",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Martian Manhunter",
    character: "Martian Manhunter",
    issue: 2,
    writer: "Deniz Camp",
    artist: "Javier Rodriguez",
    publisher: "DC",
    releaseYear: 2025,
    status: "Limited Series",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Martian Manhunter",
    character: "Martian Manhunter",
    issue: 3,
    writer: "Deniz Camp",
    artist: "Javier Rodriguez",
    publisher: "DC",
    releaseYear: 2025,
    status: "Limited Series",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Martian Manhunter",
    character: "Martian Manhunter",
    issue: 4,
    writer: "Deniz Camp",
    artist: "Javier Rodriguez",
    publisher: "DC",
    releaseYear: 2025,
    status: "Limited Series",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Martian Manhunter",
    character: "Martian Manhunter",
    issue: 5,
    writer: "Deniz Camp",
    artist: "Javier Rodriguez",
    publisher: "DC",
    releaseYear: 2025,
    status: "Limited Series",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Martian Manhunter",
    character: "Martian Manhunter",
    issue: 6,
    writer: "Deniz Camp",
    artist: "Javier Rodriguez",
    publisher: "DC",
    releaseYear: 2025,
    status: "Limited Series",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Martian Manhunter",
    character: "Martian Manhunter",
    issue: 7,
    writer: "Deniz Camp",
    artist: "Javier Rodriguez",
    publisher: "DC",
    releaseYear: 2025,
    status: "Limited Series",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Martian Manhunter",
    character: "Martian Manhunter",
    issue: 8,
    writer: "Deniz Camp",
    artist: "Javier Rodriguez",
    publisher: "DC",
    releaseYear: 2025,
    status: "Limited Series",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Martian Manhunter",
    character: "Martian Manhunter",
    issue: 9,
    writer: "Deniz Camp",
    artist: "Javier Rodriguez",
    publisher: "DC",
    releaseYear: 2025,
    status: "Limited Series",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Martian Manhunter",
    character: "Martian Manhunter",
    issue: 10,
    writer: "Deniz Camp",
    artist: "Javier Rodriguez",
    publisher: "DC",
    releaseYear: 2026,
    status: "Limited Series",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Martian Manhunter",
    character: "Martian Manhunter",
    issue: 11,
    writer: "Deniz Camp",
    artist: "Javier Rodriguez",
    publisher: "DC",
    releaseYear: 2026,
    status: "Limited Series",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Martian Manhunter",
    character: "Martian Manhunter",
    issue: 12,
    writer: "Deniz Camp",
    artist: "Javier Rodriguez",
    publisher: "DC",
    releaseYear: 2026,
    status: "Limited Series",
    genre: "Superhero",
    rating: null,
    read: false,
    owned: false
  }
];
