const comics = [
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 1,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2024,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2024-09/ABS_BM_Cv1_00111_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 2,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2024,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2024-11/ABS_BM_Cv2_00211_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 3,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2024,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2024-12/ABS_BM_Cv3_00311_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 4,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2024-12/ABS_BM_Cv4_00411_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 5,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-02/ABS_BM_Cv5_00511_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 6,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-03/ABS_BM_Cv6_00611_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 7,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-04/ABS_BM_Cv7_00711_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 8,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-05/ABS_BM_Cv8_00811_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 9,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-06/ABS_BM_Cv9_00911_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 10,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-07/ABS_BM_Cv10_01011_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 11,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-08/ABS_BM_Cv11_01111_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 12,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-09/T2349200125001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 13,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-10/T2349200135001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 14,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-11/T2349200145001_000_HD_HD.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 15,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-12/T2349200155001_000_HD_HD.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 16,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2026-01/T2349200165001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 17,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2026-02/T2349200175001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 18,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2026-03/T2349200185001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Batman",
    character: "Batman",
    issue: 19,
    writer: "Scott Snyder",
    artist: "Nick Dragotta",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2026-04/T2349200195001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 1,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2024,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2024-10/ABS_WW_Cv1_00111_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 2,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2024,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2024-11/ABS_WW_Cv2_00211_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 3,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2024,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2024-12/ABS_WW_Cv3_00311_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 4,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-01/ABS_WW_Cv4_00411_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 5,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-02/ABS_WW_Cv5_00511_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 6,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-03/ABS_WW_Cv6_00611_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 7,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-04/ABS_WW_Cv7_00711_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 8,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-05/ABS_WW_Cv8_00811_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 9,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-06/ABS_WW_Cv9_00911_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 10,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://images.comicbookroundup.com/img/covers/a/absolute-wonder-woman-(2024)/10.webp",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 11,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-08/ABS_WW_Cv11_01111_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 12,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-09/T2349400125001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 13,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-10/T2349400135001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 14,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-11/T2349400145001_000_HD_HD.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 15,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-12/T2349400155001_000_HD_HD.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 16,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2026-01/T2349400165001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 17,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2026-02/T2349400175001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Wonder Woman",
    character: "Wonder Woman",
    issue: 18,
    writer: "Kelly Thompson",
    artist: "Hayden Sherman",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2026-03/T2349400185001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 1,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2024,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2024-10/ABS_SM_Cv1_00111_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 2,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2024,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2024-12/ABS_SM_Cv2_00211_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 3,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2024-12/ABS_SM_Cv3_00311_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 4,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-02/ABS_SM_Cv4_00411_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 5,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-03/ABS_SM_Cv5_00511_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 6,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-04/ABS_SM_Cv6_00611_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 7,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-05/ABS_SM_Cv7_00711_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 8,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-06/ABS_SM_Cv8_00811_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 9,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://images.comicbookroundup.com/img/covers/a/absolute-superman-(2024)/9.webp",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 10,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-08/ABS_SM_Cv10_01011_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 11,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-09/T2349300115001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 12,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-10/T2349300125001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 13,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-11/T2349300135001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 14,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-12/T2349300145001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 15,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2026-01/T2349300155001_000_HD_HD.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 16,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2026-02/T2349300165001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 17,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2026-03/T2349300175001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Superman",
    character: "Superman",
    issue: 18,
    writer: "Jason Aaron",
    artist: "Rafa Sandoval",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2026-03/T2349300185001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Flash",
    character: "Flash",
    issue: 1,
    writer: "Jeff Lemire",
    artist: "Nick Robles",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-03/AB_FLS_Cv1_00111_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Flash",
    character: "Flash",
    issue: 2,
    writer: "Jeff Lemire",
    artist: "Nick Robles",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-04/AB_FLS_Cv2_00211_R1.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Flash",
    character: "Flash",
    issue: 3,
    writer: "Jeff Lemire",
    artist: "Nick Robles",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-05/AB_FLS_Cv3_00311_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Flash",
    character: "Flash",
    issue: 4,
    writer: "Jeff Lemire",
    artist: "Nick Robles",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-06/AB_FLS_Cv4_00411_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Flash",
    character: "Flash",
    issue: 5,
    writer: "Jeff Lemire",
    artist: "Nick Robles",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-07/AB_FLS_Cv5_00511_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Flash",
    character: "Flash",
    issue: 6,
    writer: "Jeff Lemire",
    artist: "Nick Robles",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-08/AB_FLS_Cv6_00611_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Flash",
    character: "Flash",
    issue: 7,
    writer: "Jeff Lemire",
    artist: "Nick Robles",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-09/T2385700075001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Flash",
    character: "Flash",
    issue: 8,
    writer: "Jeff Lemire",
    artist: "Nick Robles",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-10/T2385700085001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Flash",
    character: "Flash",
    issue: 9,
    writer: "Jeff Lemire",
    artist: "Nick Robles",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-11/T2385700095001_000_HD_HD.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Flash",
    character: "Flash",
    issue: 10,
    writer: "Jeff Lemire",
    artist: "Nick Robles",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-12/T2385700105001_000_HD_HD.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Flash",
    character: "Flash",
    issue: 11,
    writer: "Jeff Lemire",
    artist: "Nick Robles",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2026-01/T2385700115001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Flash",
    character: "Flash",
    issue: 12,
    writer: "Jeff Lemire",
    artist: "Nick Robles",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2026-03/T2385700125001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Flash",
    character: "Flash",
    issue: 13,
    writer: "Jeff Lemire",
    artist: "Nick Robles",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://images.comicbookroundup.com/img/covers/a/absolute-flash-(2025)/13.webp",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Green Lantern",
    character: "Green Lantern",
    issue: 1,
    writer: "Al Ewing",
    artist: "Jahnoy Lindsay",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-04/ABS_GL_Cv1_00111_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Green Lantern",
    character: "Green Lantern",
    issue: 2,
    writer: "Al Ewing",
    artist: "Jahnoy Lindsay",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-05/ABS_GL_Cv2_00211_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Green Lantern",
    character: "Green Lantern",
    issue: 3,
    writer: "Al Ewing",
    artist: "Jahnoy Lindsay",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-06/ABS-GL_Cv3_00311_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Green Lantern",
    character: "Green Lantern",
    issue: 4,
    writer: "Al Ewing",
    artist: "Jahnoy Lindsay",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-07/ABS-GL_Cv4_00411_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Green Lantern",
    character: "Green Lantern",
    issue: 5,
    writer: "Al Ewing",
    artist: "Jahnoy Lindsay",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-08/ABS-GL_Cv5_00511_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Green Lantern",
    character: "Green Lantern",
    issue: 6,
    writer: "Al Ewing",
    artist: "Jahnoy Lindsay",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-09/T2356500065001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Green Lantern",
    character: "Green Lantern",
    issue: 7,
    writer: "Al Ewing",
    artist: "Jahnoy Lindsay",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-09/T2356500075001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Green Lantern",
    character: "Green Lantern",
    issue: 8,
    writer: "Al Ewing",
    artist: "Jahnoy Lindsay",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-11/T2356500085001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Green Lantern",
    character: "Green Lantern",
    issue: 9,
    writer: "Al Ewing",
    artist: "Jahnoy Lindsay",
    publisher: "DC",
    releaseYear: 2025,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-12/T2356500095001_000_HD_HD.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Green Lantern",
    character: "Green Lantern",
    issue: 10,
    writer: "Al Ewing",
    artist: "Jahnoy Lindsay",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2026-01/T2356500105001_000_HD_HD.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Green Lantern",
    character: "Green Lantern",
    issue: 11,
    writer: "Al Ewing",
    artist: "Jahnoy Lindsay",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2026-02/T2356500115001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Green Lantern",
    character: "Green Lantern",
    issue: 12,
    writer: "Al Ewing",
    artist: "Jahnoy Lindsay",
    publisher: "DC",
    releaseYear: 2026,
    status: "Ongoing",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2026-03/T2356500125001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Martian Manhunter",
    character: "Martian Manhunter",
    issue: 1,
    writer: "Deniz Camp",
    artist: "Javier Rodriguez",
    publisher: "DC",
    releaseYear: 2025,
    status: "Limited Series",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-03/ABS-MM_Cv1_00111_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Martian Manhunter",
    character: "Martian Manhunter",
    issue: 2,
    writer: "Deniz Camp",
    artist: "Javier Rodriguez",
    publisher: "DC",
    releaseYear: 2025,
    status: "Limited Series",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-04/ABS-MM_Cv2_00211_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Martian Manhunter",
    character: "Martian Manhunter",
    issue: 3,
    writer: "Deniz Camp",
    artist: "Javier Rodriguez",
    publisher: "DC",
    releaseYear: 2025,
    status: "Limited Series",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-05/ABS-MM_Cv3_00311_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Martian Manhunter",
    character: "Martian Manhunter",
    issue: 4,
    writer: "Deniz Camp",
    artist: "Javier Rodriguez",
    publisher: "DC",
    releaseYear: 2025,
    status: "Limited Series",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-06/ABS-MM_Cv4_00411_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Martian Manhunter",
    character: "Martian Manhunter",
    issue: 5,
    writer: "Deniz Camp",
    artist: "Javier Rodriguez",
    publisher: "DC",
    releaseYear: 2025,
    status: "Limited Series",
    genre: "Superhero",
    coverImage: "https://images.comicbookroundup.com/img/covers/a/absolute-martian-manhunter-(2025)/5.webp",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Martian Manhunter",
    character: "Martian Manhunter",
    issue: 6,
    writer: "Deniz Camp",
    artist: "Javier Rodriguez",
    publisher: "DC",
    releaseYear: 2025,
    status: "Limited Series",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-08/ABS-MM_Cv6_00611_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Martian Manhunter",
    character: "Martian Manhunter",
    issue: 7,
    writer: "Deniz Camp",
    artist: "Javier Rodriguez",
    publisher: "DC",
    releaseYear: 2025,
    status: "Limited Series",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-12/T2385300075001_000_HD_HD.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Martian Manhunter",
    character: "Martian Manhunter",
    issue: 8,
    writer: "Deniz Camp",
    artist: "Javier Rodriguez",
    publisher: "DC",
    releaseYear: 2026,
    status: "Limited Series",
    genre: "Superhero",
    coverImage: "https://bleedingcool.com/wp-content/uploads/2026/01/1125DC0067.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Martian Manhunter",
    character: "Martian Manhunter",
    issue: 9,
    writer: "Deniz Camp",
    artist: "Javier Rodriguez",
    publisher: "DC",
    releaseYear: 2026,
    status: "Limited Series",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2026-02/T2385300095001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Martian Manhunter",
    character: "Martian Manhunter",
    issue: 10,
    writer: "Deniz Camp",
    artist: "Javier Rodriguez",
    publisher: "DC",
    releaseYear: 2026,
    status: "Limited Series",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2026-03/T2385300105001.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Martian Manhunter",
    character: "Martian Manhunter",
    issue: 11,
    writer: "Deniz Camp",
    artist: "Javier Rodriguez",
    publisher: "DC",
    releaseYear: 2026,
    status: "Limited Series",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-03/ABS-MM_Cv1_00111_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  },
  {
    title: "Absolute Martian Manhunter",
    character: "Martian Manhunter",
    issue: 12,
    writer: "Deniz Camp",
    artist: "Javier Rodriguez",
    publisher: "DC",
    releaseYear: 2026,
    status: "Limited Series",
    genre: "Superhero",
    coverImage: "https://static.dc.com/2025-03/ABS-MM_Cv1_00111_DIGITAL.jpg",
    rating: null,
    read: false,
    owned: false
  }
];
